name: Run Python Script

on:
  push:
    branches:
      - main  # O la rama que desees
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest  # Puedes usar ubuntu-latest o windows-latest según sea necesario

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Especifica la versión de Python que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de tener un archivo requirements.txt en tu repositorio

    - name: Run the script
      env:  # Establece las variables de entorno necesarias
        MY_USERNAME: ${{ secrets.MY_USERNAME }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python ../scrapper_date.py
