name: Run EXE

on:
  push:
    branches:
      - main  # O la rama que desees
  pull_request:

jobs:
  run-exe:
    runs-on: windows-latest  # Asegúrate de usar un runner de Windows

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run the EXE
      run: |
        .\scrapper_date
